//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionProbeConfig) DeepCopyInto(out *AdmissionProbeConfig) {
	*out = *in
	if in.KnownBadSpec != nil {
		in, out := &in.KnownBadSpec, &out.KnownBadSpec
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionProbeConfig.
func (in *AdmissionProbeConfig) DeepCopy() *AdmissionProbeConfig {
	if in == nil {
		return nil
	}
	out := new(AdmissionProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProbeConfig) DeepCopyInto(out *CustomProbeConfig) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProbeConfig.
func (in *CustomProbeConfig) DeepCopy() *CustomProbeConfig {
	if in == nil {
		return nil
	}
	out := new(CustomProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeResultAudit) DeepCopyInto(out *ProbeResultAudit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeResultAudit.
func (in *ProbeResultAudit) DeepCopy() *ProbeResultAudit {
	if in == nil {
		return nil
	}
	out := new(ProbeResultAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeResultExecution) DeepCopyInto(out *ProbeResultExecution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeResultExecution.
func (in *ProbeResultExecution) DeepCopy() *ProbeResultExecution {
	if in == nil {
		return nil
	}
	out := new(ProbeResultExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeResultProbeRef) DeepCopyInto(out *ProbeResultProbeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeResultProbeRef.
func (in *ProbeResultProbeRef) DeepCopy() *ProbeResultProbeRef {
	if in == nil {
		return nil
	}
	out := new(ProbeResultProbeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeResultResult) DeepCopyInto(out *ProbeResultResult) {
	*out = *in
	if in.ControlMappings != nil {
		in, out := &in.ControlMappings, &out.ControlMappings
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.NistControls != nil {
		in, out := &in.NistControls, &out.NistControls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeResultResult.
func (in *ProbeResultResult) DeepCopy() *ProbeResultResult {
	if in == nil {
		return nil
	}
	out := new(ProbeResultResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeResultSummary) DeepCopyInto(out *ProbeResultSummary) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeResultSummary.
func (in *ProbeResultSummary) DeepCopy() *ProbeResultSummary {
	if in == nil {
		return nil
	}
	out := new(ProbeResultSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportTimeRange) DeepCopyInto(out *ReportTimeRange) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = (*in).DeepCopy()
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportTimeRange.
func (in *ReportTimeRange) DeepCopy() *ReportTimeRange {
	if in == nil {
		return nil
	}
	out := new(ReportTimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealAOAuthorization) DeepCopyInto(out *SiderealAOAuthorization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealAOAuthorization.
func (in *SiderealAOAuthorization) DeepCopy() *SiderealAOAuthorization {
	if in == nil {
		return nil
	}
	out := new(SiderealAOAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealAOAuthorization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealAOAuthorizationList) DeepCopyInto(out *SiderealAOAuthorizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealAOAuthorization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealAOAuthorizationList.
func (in *SiderealAOAuthorizationList) DeepCopy() *SiderealAOAuthorizationList {
	if in == nil {
		return nil
	}
	out := new(SiderealAOAuthorizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealAOAuthorizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealAOAuthorizationSpec) DeepCopyInto(out *SiderealAOAuthorizationSpec) {
	*out = *in
	if in.AuthorizedTechniques != nil {
		in, out := &in.AuthorizedTechniques, &out.AuthorizedTechniques
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedNamespaces != nil {
		in, out := &in.AuthorizedNamespaces, &out.AuthorizedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ValidFrom.DeepCopyInto(&out.ValidFrom)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealAOAuthorizationSpec.
func (in *SiderealAOAuthorizationSpec) DeepCopy() *SiderealAOAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealAOAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealAOAuthorizationStatus) DeepCopyInto(out *SiderealAOAuthorizationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealAOAuthorizationStatus.
func (in *SiderealAOAuthorizationStatus) DeepCopy() *SiderealAOAuthorizationStatus {
	if in == nil {
		return nil
	}
	out := new(SiderealAOAuthorizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealIncident) DeepCopyInto(out *SiderealIncident) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealIncident.
func (in *SiderealIncident) DeepCopy() *SiderealIncident {
	if in == nil {
		return nil
	}
	out := new(SiderealIncident)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealIncident) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealIncidentList) DeepCopyInto(out *SiderealIncidentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealIncident, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealIncidentList.
func (in *SiderealIncidentList) DeepCopy() *SiderealIncidentList {
	if in == nil {
		return nil
	}
	out := new(SiderealIncidentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealIncidentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealIncidentSpec) DeepCopyInto(out *SiderealIncidentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealIncidentSpec.
func (in *SiderealIncidentSpec) DeepCopy() *SiderealIncidentSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealIncidentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbe) DeepCopyInto(out *SiderealProbe) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbe.
func (in *SiderealProbe) DeepCopy() *SiderealProbe {
	if in == nil {
		return nil
	}
	out := new(SiderealProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbe) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeList) DeepCopyInto(out *SiderealProbeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealProbe, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeList.
func (in *SiderealProbeList) DeepCopy() *SiderealProbeList {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeRecommendation) DeepCopyInto(out *SiderealProbeRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeRecommendation.
func (in *SiderealProbeRecommendation) DeepCopy() *SiderealProbeRecommendation {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbeRecommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeRecommendationList) DeepCopyInto(out *SiderealProbeRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealProbeRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeRecommendationList.
func (in *SiderealProbeRecommendationList) DeepCopy() *SiderealProbeRecommendationList {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeRecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbeRecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeRecommendationSpec) DeepCopyInto(out *SiderealProbeRecommendationSpec) {
	*out = *in
	out.SourceResource = in.SourceResource
	in.ProbeTemplate.DeepCopyInto(&out.ProbeTemplate)
	if in.ControlMappings != nil {
		in, out := &in.ControlMappings, &out.ControlMappings
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeRecommendationSpec.
func (in *SiderealProbeRecommendationSpec) DeepCopy() *SiderealProbeRecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeRecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeRecommendationStatus) DeepCopyInto(out *SiderealProbeRecommendationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeRecommendationStatus.
func (in *SiderealProbeRecommendationStatus) DeepCopy() *SiderealProbeRecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeRecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeResult) DeepCopyInto(out *SiderealProbeResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeResult.
func (in *SiderealProbeResult) DeepCopy() *SiderealProbeResult {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbeResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeResultList) DeepCopyInto(out *SiderealProbeResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealProbeResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeResultList.
func (in *SiderealProbeResultList) DeepCopy() *SiderealProbeResultList {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealProbeResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeResultSpec) DeepCopyInto(out *SiderealProbeResultSpec) {
	*out = *in
	out.Probe = in.Probe
	in.Result.DeepCopyInto(&out.Result)
	out.Execution = in.Execution
	out.Audit = in.Audit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeResultSpec.
func (in *SiderealProbeResultSpec) DeepCopy() *SiderealProbeResultSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeSpec) DeepCopyInto(out *SiderealProbeSpec) {
	*out = *in
	if in.TargetNamespaceSelector != nil {
		in, out := &in.TargetNamespaceSelector, &out.TargetNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlMappings != nil {
		in, out := &in.ControlMappings, &out.ControlMappings
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.AdmissionProbe != nil {
		in, out := &in.AdmissionProbe, &out.AdmissionProbe
		*out = new(AdmissionProbeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomProbe != nil {
		in, out := &in.CustomProbe, &out.CustomProbe
		*out = new(CustomProbeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeSpec.
func (in *SiderealProbeSpec) DeepCopy() *SiderealProbeSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealProbeStatus) DeepCopyInto(out *SiderealProbeStatus) {
	*out = *in
	if in.LastExecutedAt != nil {
		in, out := &in.LastExecutedAt, &out.LastExecutedAt
		*out = (*in).DeepCopy()
	}
	if in.RecentResults != nil {
		in, out := &in.RecentResults, &out.RecentResults
		*out = make([]ProbeResultSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealProbeStatus.
func (in *SiderealProbeStatus) DeepCopy() *SiderealProbeStatus {
	if in == nil {
		return nil
	}
	out := new(SiderealProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealReport) DeepCopyInto(out *SiderealReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealReport.
func (in *SiderealReport) DeepCopy() *SiderealReport {
	if in == nil {
		return nil
	}
	out := new(SiderealReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealReportList) DeepCopyInto(out *SiderealReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealReportList.
func (in *SiderealReportList) DeepCopy() *SiderealReportList {
	if in == nil {
		return nil
	}
	out := new(SiderealReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealReportSpec) DeepCopyInto(out *SiderealReportSpec) {
	*out = *in
	if in.Frameworks != nil {
		in, out := &in.Frameworks, &out.Frameworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimeRange != nil {
		in, out := &in.TimeRange, &out.TimeRange
		*out = new(ReportTimeRange)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealReportSpec.
func (in *SiderealReportSpec) DeepCopy() *SiderealReportSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealReportStatus) DeepCopyInto(out *SiderealReportStatus) {
	*out = *in
	if in.LastGeneratedAt != nil {
		in, out := &in.LastGeneratedAt, &out.LastGeneratedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealReportStatus.
func (in *SiderealReportStatus) DeepCopy() *SiderealReportStatus {
	if in == nil {
		return nil
	}
	out := new(SiderealReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealSystemAlert) DeepCopyInto(out *SiderealSystemAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealSystemAlert.
func (in *SiderealSystemAlert) DeepCopy() *SiderealSystemAlert {
	if in == nil {
		return nil
	}
	out := new(SiderealSystemAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealSystemAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealSystemAlertList) DeepCopyInto(out *SiderealSystemAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiderealSystemAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealSystemAlertList.
func (in *SiderealSystemAlertList) DeepCopy() *SiderealSystemAlertList {
	if in == nil {
		return nil
	}
	out := new(SiderealSystemAlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiderealSystemAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiderealSystemAlertSpec) DeepCopyInto(out *SiderealSystemAlertSpec) {
	*out = *in
	if in.AcknowledgedAt != nil {
		in, out := &in.AcknowledgedAt, &out.AcknowledgedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiderealSystemAlertSpec.
func (in *SiderealSystemAlertSpec) DeepCopy() *SiderealSystemAlertSpec {
	if in == nil {
		return nil
	}
	out := new(SiderealSystemAlertSpec)
	in.DeepCopyInto(out)
	return out
}
