package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"sigs.k8s.io/controller-runtime/pkg/metrics"
)

var (
	// ProbeExecutionsTotal counts probe executions by type, outcome, and effectiveness.
	ProbeExecutionsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "sidereal_probe_executions_total",
			Help: "Total number of probe executions",
		},
		[]string{"probe_type", "outcome", "control_effectiveness"},
	)

	// ProbeFailuresTotal counts probe failures by type.
	ProbeFailuresTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "sidereal_probe_failures_total",
			Help: "Total number of probe execution failures (infrastructure, not control failures)",
		},
		[]string{"probe_type"},
	)

	// ConsecutiveFailures tracks consecutive non-Effective results per probe and namespace.
	ConsecutiveFailures = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "sidereal_consecutive_failures",
			Help: "Number of consecutive non-Effective results",
		},
		[]string{"probe_type", "target_namespace"},
	)

	// SIEMExportFailuresTotal counts SIEM export failures by backend.
	SIEMExportFailuresTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "sidereal_siem_export_failures_total",
			Help: "Total number of SIEM export failures",
		},
		[]string{"backend"},
	)

	// HMACVerificationFailuresTotal counts HMAC verification failures.
	HMACVerificationFailuresTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "sidereal_hmac_verification_failures_total",
			Help: "Total number of HMAC verification failures (tamper detection)",
		},
	)

	// ProbeDurationSeconds tracks probe execution duration.
	ProbeDurationSeconds = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "sidereal_probe_duration_seconds",
			Help:    "Probe execution duration in seconds",
			Buckets: prometheus.ExponentialBuckets(0.1, 2, 12),
		},
		[]string{"probe_type"},
	)

	// BootstrapVerificationStatus indicates bootstrap verification result (1=passed, 0=failed).
	BootstrapVerificationStatus = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "sidereal_bootstrap_verification_status",
			Help: "Bootstrap verification status (1=passed, 0=failed)",
		},
	)

	// DiscoveryRecommendationsTotal counts discovery-generated recommendations.
	DiscoveryRecommendationsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "sidereal_discovery_recommendations_total",
			Help: "Total number of probe recommendations generated by discovery",
		},
		[]string{"probe_type", "confidence"},
	)

	// ReportGenerationsTotal counts report generation attempts.
	ReportGenerationsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "sidereal_report_generations_total",
			Help: "Total number of report generation attempts",
		},
		[]string{"report_type", "status"},
	)
)

func init() {
	metrics.Registry.MustRegister(
		ProbeExecutionsTotal,
		ProbeFailuresTotal,
		ConsecutiveFailures,
		SIEMExportFailuresTotal,
		HMACVerificationFailuresTotal,
		ProbeDurationSeconds,
		BootstrapVerificationStatus,
		DiscoveryRecommendationsTotal,
		ReportGenerationsTotal,
	)
}
